const delay = (ms) => new Promise((res) => setTimeout(res, ms));

// Data to scrape.
db = {
  geo: [
    [`Tokyo, Japan`, `Tokyo, Japan`, null, null, null],
    [`Jakarta, Indonesia`, `Jakarta, Indonesia`, null, null, null],
    [`Delhi, India`, `Delhi, India`, null, null, null],
    [`Mumbai, India`, `Mumbai, India`, null, null, null],
    [`Manila, Philippines`, `Manila, Philippines`, null, null, null],
    [`Shanghai, China`, `Shanghai, China`, null, null, null],
    [`Sao Paulo, Brazil`, `Sao Paulo, Brazil`, null, null, null],
    [`Seoul, Korea, South`, `Seoul, Korea, South`, null, null, null],
    [`Mexico City, Mexico`, `Mexico City, Mexico`, null, null, null],
    [`Guangzhou, China`, `Guangzhou, China`, null, null, null],
    [`Beijing, China`, `Beijing, China`, null, null, null],
    [`Cairo, Egypt`, `Cairo, Egypt`, null, null, null],
    [`New York, United States`, `New York, United States`, null, null, null],
    [`Kolkata, India`, `Kolkata, India`, null, null, null],
    [`Moscow, Russia`, `Moscow, Russia`, null, null, null],
    [`Bangkok, Thailand`, `Bangkok, Thailand`, null, null, null],
    [`Buenos Aires, Argentina`, `Buenos Aires, Argentina`, null, null, null],
    [`Shenzhen, China`, `Shenzhen, China`, null, null, null],
    [`Dhaka, Bangladesh`, `Dhaka, Bangladesh`, null, null, null],
    [`Lagos, Nigeria`, `Lagos, Nigeria`, null, null, null],
    [`Istanbul, Turkey`, `Istanbul, Turkey`, null, null, null],
    [`Osaka, Japan`, `Osaka, Japan`, null, null, null],
    [`Karachi, Pakistan`, `Karachi, Pakistan`, null, null, null],
    [`Bangalore, India`, `Bangalore, India`, null, null, null],
    [`Tehran, Iran`, `Tehran, Iran`, null, null, null],
    [
      `Kinshasa, Congo (Kinshasa)`,
      `Kinshasa, Congo (Kinshasa)`,
      null,
      null,
      null,
    ],
    [
      `Ho Chi Minh City, Vietnam`,
      `Ho Chi Minh City, Vietnam`,
      null,
      null,
      null,
    ],
    [
      `Los Angeles, United States`,
      `Los Angeles, United States`,
      null,
      null,
      null,
    ],
    [`Rio de Janeiro, Brazil`, `Rio de Janeiro, Brazil`, null, null, null],
    [`Nanyang, China`, `Nanyang, China`, null, null, null],
    [`Chennai, India`, `Chennai, India`, null, null, null],
    [`Chengdu, China`, `Chengdu, China`, null, null, null],
    [`Lahore, Pakistan`, `Lahore, Pakistan`, null, null, null],
    [`Paris, France`, `Paris, France`, null, null, null],
    [`London, United Kingdom`, `London, United Kingdom`, null, null, null],
    [`Linyi, China`, `Linyi, China`, null, null, null],
    [`Tianjin, China`, `Tianjin, China`, null, null, null],
    [`Shijiazhuang, China`, `Shijiazhuang, China`, null, null, null],
    [`Baoding, China`, `Baoding, China`, null, null, null],
    [`Zhoukou, China`, `Zhoukou, China`, null, null, null],
    [`Lima, Peru`, `Lima, Peru`, null, null, null],
    [`Hyderabad, India`, `Hyderabad, India`, null, null, null],
    [`Bogota, Colombia`, `Bogota, Colombia`, null, null, null],
    [`Weifang, China`, `Weifang, China`, null, null, null],
    [`Nagoya, Japan`, `Nagoya, Japan`, null, null, null],
    [`Wuhan, China`, `Wuhan, China`, null, null, null],
    [`Heze, China`, `Heze, China`, null, null, null],
    [`Ganzhou, China`, `Ganzhou, China`, null, null, null],
    [`Tongshan, China`, `Tongshan, China`, null, null, null],
    [`Chicago, United States`, `Chicago, United States`, null, null, null],
    [`Handan, China`, `Handan, China`, null, null, null],
    [`Luanda, Angola`, `Luanda, Angola`, null, null, null],
    [`Fuyang, China`, `Fuyang, China`, null, null, null],
    [`Kuala Lumpur, Malaysia`, `Kuala Lumpur, Malaysia`, null, null, null],
    [`Jining, China`, `Jining, China`, null, null, null],
    [`Hanoi, Vietnam`, `Hanoi, Vietnam`, null, null, null],
    [`Pune, India`, `Pune, India`, null, null, null],
    [`Onitsha, Nigeria`, `Onitsha, Nigeria`, null, null, null],
    [`Ahmadabad, India`, `Ahmadabad, India`, null, null, null],
    [`Hong Kong, Hong Kong`, `Hong Kong, Hong Kong`, null, null, null],
    [`Khartoum, Sudan`, `Khartoum, Sudan`, null, null, null],
    [`Santiago, Chile`, `Santiago, Chile`, null, null, null],
    [`Riyadh, Saudi Arabia`, `Riyadh, Saudi Arabia`, null, null, null],
    [`Dar es Salaam, Tanzania`, `Dar es Salaam, Tanzania`, null, null, null],
    [`Miami, United States`, `Miami, United States`, null, null, null],
    [`Surat, India`, `Surat, India`, null, null, null],
    [`Baghdad, Iraq`, `Baghdad, Iraq`, null, null, null],
    [`Singapore, Singapore`, `Singapore, Singapore`, null, null, null],
    [`Dallas, United States`, `Dallas, United States`, null, null, null],
    [
      `Philadelphia, United States`,
      `Philadelphia, United States`,
      null,
      null,
      null,
    ],
    [`Nairobi, Kenya`, `Nairobi, Kenya`, null, null, null],
    [`Ankara, Turkey`, `Ankara, Turkey`, null, null, null],
    [`Houston, United States`, `Houston, United States`, null, null, null],
    [`Atlanta, United States`, `Atlanta, United States`, null, null, null],
    [`Rangoon, Burma`, `Rangoon, Burma`, null, null, null],
    [`Toronto, Canada`, `Toronto, Canada`, null, null, null],
    [
      `Washington, United States`,
      `Washington, United States`,
      null,
      null,
      null,
    ],
    [`Saint Petersburg, Russia`, `Saint Petersburg, Russia`, null, null, null],
    [`Sydney, Australia`, `Sydney, Australia`, null, null, null],
    [`Guadalajara, Mexico`, `Guadalajara, Mexico`, null, null, null],
    [`Belo Horizonte, Brazil`, `Belo Horizonte, Brazil`, null, null, null],
    [`Melbourne, Australia`, `Melbourne, Australia`, null, null, null],
    [`Surabaya, Indonesia`, `Surabaya, Indonesia`, null, null, null],
    [`Abidjan, Côte D’Ivoire`, `Abidjan, Côte D’Ivoire`, null, null, null],
    [`Alexandria, Egypt`, `Alexandria, Egypt`, null, null, null],
    [`Boston, United States`, `Boston, United States`, null, null, null],
    [`Barcelona, Spain`, `Barcelona, Spain`, null, null, null],
    [
      `Johannesburg, South Africa`,
      `Johannesburg, South Africa`,
      null,
      null,
      null,
    ],
    [`Casablanca, Morocco`, `Casablanca, Morocco`, null, null, null],
    [`Izmir, Turkey`, `Izmir, Turkey`, null, null, null],
    [`Monterrey, Mexico`, `Monterrey, Mexico`, null, null, null],
    [`Phoenix, United States`, `Phoenix, United States`, null, null, null],
    [`Amman, Jordan`, `Amman, Jordan`, null, null, null],
    [`Jeddah, Saudi Arabia`, `Jeddah, Saudi Arabia`, null, null, null],
    [`Sialkot City, Pakistan`, `Sialkot City, Pakistan`, null, null, null],
    [`Seattle, United States`, `Seattle, United States`, null, null, null],
    [`Yokohama, Japan`, `Yokohama, Japan`, null, null, null],
    [`Kabul, Afghanistan`, `Kabul, Afghanistan`, null, null, null],
    [`Berlin, Germany`, `Berlin, Germany`, null, null, null],
    [
      `San Francisco, United States`,
      `San Francisco, United States`,
      null,
      null,
      null,
    ],
    [`Montreal, Canada`, `Montreal, Canada`, null, null, null],
    [`Detroit, United States`, `Detroit, United States`, null, null, null],
    [`Busan, Korea, South`, `Busan, Korea, South`, null, null, null],
    [`Algiers, Algeria`, `Algiers, Algeria`, null, null, null],
    [`Lucknow, India`, `Lucknow, India`, null, null, null],
    [`Madrid, Spain`, `Madrid, Spain`, null, null, null],
    [`San Diego, United States`, `San Diego, United States`, null, null, null],
    [`Faisalabad, Pakistan`, `Faisalabad, Pakistan`, null, null, null],
    [`Santa Cruz, Bolivia`, `Santa Cruz, Bolivia`, null, null, null],
    [`Jaipur, India`, `Jaipur, India`, null, null, null],
    [`Addis Ababa, Ethiopia`, `Addis Ababa, Ethiopia`, null, null, null],
    [`Giza, Egypt`, `Giza, Egypt`, null, null, null],
    [`Brasilia, Brazil`, `Brasilia, Brazil`, null, null, null],
    [`Mashhad, Iran`, `Mashhad, Iran`, null, null, null],
    [
      `Minneapolis, United States`,
      `Minneapolis, United States`,
      null,
      null,
      null,
    ],
    [`Kyiv, Ukraine`, `Kyiv, Ukraine`, null, null, null],
    [`Sanaa, Yemen`, `Sanaa, Yemen`, null, null, null],
    [`Quezon City, Philippines`, `Quezon City, Philippines`, null, null, null],
    [`Salvador, Brazil`, `Salvador, Brazil`, null, null, null],
    [`Incheon, Korea, South`, `Incheon, Korea, South`, null, null, null],
    [`Bursa, Turkey`, `Bursa, Turkey`, null, null, null],
    [`Tampa, United States`, `Tampa, United States`, null, null, null],
    [
      `Birmingham, United Kingdom`,
      `Birmingham, United Kingdom`,
      null,
      null,
      null,
    ],
    [`Denver, United States`, `Denver, United States`, null, null, null],
    [`Rome, Italy`, `Rome, Italy`, null, null, null],
    [`La Paz, Bolivia`, `La Paz, Bolivia`, null, null, null],
    [`Pyongyang, Korea, North`, `Pyongyang, Korea, North`, null, null, null],
    [`Kano, Nigeria`, `Kano, Nigeria`, null, null, null],
    [`Taichung, Taiwan`, `Taichung, Taiwan`, null, null, null],
    [`Omdurman, Sudan`, `Omdurman, Sudan`, null, null, null],
    [`Kaohsiung, Taiwan`, `Kaohsiung, Taiwan`, null, null, null],
    [`Guayaquil, Ecuador`, `Guayaquil, Ecuador`, null, null, null],
    [
      `Manchester, United Kingdom`,
      `Manchester, United Kingdom`,
      null,
      null,
      null,
    ],
    [`Cawnpore, India`, `Cawnpore, India`, null, null, null],
    [`Taipei, Taiwan`, `Taipei, Taiwan`, null, null, null],
    [`Ibadan, Nigeria`, `Ibadan, Nigeria`, null, null, null],
    [`Antananarivo, Madagascar`, `Antananarivo, Madagascar`, null, null, null],
    [`Chattogram, Bangladesh`, `Chattogram, Bangladesh`, null, null, null],
    [
      `Santo Domingo, Dominican Republic`,
      `Santo Domingo, Dominican Republic`,
      null,
      null,
      null,
    ],
    [`Brooklyn, United States`, `Brooklyn, United States`, null, null, null],
    [`Medellin, Colombia`, `Medellin, Colombia`, null, null, null],
    [`Brisbane, Australia`, `Brisbane, Australia`, null, null, null],
    [
      `Dubai, United Arab Emirates`,
      `Dubai, United Arab Emirates`,
      null,
      null,
      null,
    ],
    [`Mirzapur, India`, `Mirzapur, India`, null, null, null],
    [`Cali, Colombia`, `Cali, Colombia`, null, null, null],
    [`Daegu, Korea, South`, `Daegu, Korea, South`, null, null, null],
    [`Fortaleza, Brazil`, `Fortaleza, Brazil`, null, null, null],
    [
      `Guatemala City, Guatemala`,
      `Guatemala City, Guatemala`,
      null,
      null,
      null,
    ],
    [`Yaounde, Cameroon`, `Yaounde, Cameroon`, null, null, null],
    [`Douala, Cameroon`, `Douala, Cameroon`, null, null, null],
    [`Antalya, Turkey`, `Antalya, Turkey`, null, null, null],
    [`Tashkent, Uzbekistan`, `Tashkent, Uzbekistan`, null, null, null],
    [`Bandung, Indonesia`, `Bandung, Indonesia`, null, null, null],
    [`Nagpur, India`, `Nagpur, India`, null, null, null],
    [`Bekasi, Indonesia`, `Bekasi, Indonesia`, null, null, null],
    [`Ghaziabad, India`, `Ghaziabad, India`, null, null, null],
    [`Tijuana, Mexico`, `Tijuana, Mexico`, null, null, null],
    [`Accra, Ghana`, `Accra, Ghana`, null, null, null],
    [`Vancouver, Canada`, `Vancouver, Canada`, null, null, null],
    [`Tangerang, Indonesia`, `Tangerang, Indonesia`, null, null, null],
    [`Konya, Turkey`, `Konya, Turkey`, null, null, null],
    [`Queens, United States`, `Queens, United States`, null, null, null],
    [`Adana, Turkey`, `Adana, Turkey`, null, null, null],
    [`Medan, Indonesia`, `Medan, Indonesia`, null, null, null],
    [`Indore, India`, `Indore, India`, null, null, null],
    [`Baku, Azerbaijan`, `Baku, Azerbaijan`, null, null, null],
    [`Havana, Cuba`, `Havana, Cuba`, null, null, null],
    [`Phnom Penh, Cambodia`, `Phnom Penh, Cambodia`, null, null, null],
    [`Fukuoka, Japan`, `Fukuoka, Japan`, null, null, null],
    [`Mogadishu, Somalia`, `Mogadishu, Somalia`, null, null, null],
    [`Riverside, United States`, `Riverside, United States`, null, null, null],
    [`Baltimore, United States`, `Baltimore, United States`, null, null, null],
    [`Haiphong, Vietnam`, `Haiphong, Vietnam`, null, null, null],
    [`Las Vegas, United States`, `Las Vegas, United States`, null, null, null],
    [`Rawalpindi, Pakistan`, `Rawalpindi, Pakistan`, null, null, null],
    [`Kumasi, Ghana`, `Kumasi, Ghana`, null, null, null],
    [`Portland, United States`, `Portland, United States`, null, null, null],
    [`Vadodara, India`, `Vadodara, India`, null, null, null],
    [`Perth, Australia`, `Perth, Australia`, null, null, null],
    [
      `San Antonio, United States`,
      `San Antonio, United States`,
      null,
      null,
      null,
    ],
    [`Vishakhapatnam, India`, `Vishakhapatnam, India`, null, null, null],
    [`Gaziantep, Turkey`, `Gaziantep, Turkey`, null, null, null],
    [`Minsk, Belarus`, `Minsk, Belarus`, null, null, null],
    [`St. Louis, United States`, `St. Louis, United States`, null, null, null],
    [`Bamako, Mali`, `Bamako, Mali`, null, null, null],
    [`Quito, Ecuador`, `Quito, Ecuador`, null, null, null],
  ],
};

// Data to scrape.
// db = {
//   geo: [
//     [
//       `22nd Street Skytrain Station, Vancouver, Canada`,
//       `22nd Street Skytrain Station, Vancouver, Canada`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `29th Avenue Skytrain Station, Vancouver, Canada`,
//       `29th Avenue Skytrain Station, Vancouver, Canada`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Aberdeen Skytrain Station, Vancouver, Canada`,
//       `Aberdeen Skytrain Station, Vancouver, Canada`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Braid Skytrain Station, Vancouver, Canada`,
//       `Braid Skytrain Station, Vancouver, Canada`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Brentwood Town Centre Skytrain Station, Vancouver, Canada`,
//       `Brentwood Town Centre Skytrain Station, Vancouver, Canada`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Bridgeport Skytrain Station, Vancouver, Canada`,
//       `Bridgeport Skytrain Station, Vancouver, Canada`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Broadway–City Hall Skytrain Station, Vancouver, Canada`,
//       `Broadway–City Hall Skytrain Station, Vancouver, Canada`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Burquitlam Skytrain Station, Vancouver, Canada`,
//       `Burquitlam Skytrain Station, Vancouver, Canada`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Burrard Skytrain Station, Vancouver, Canada`,
//       `Burrard Skytrain Station, Vancouver, Canada`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Columbia Skytrain Station, Vancouver, Canada`,
//       `Columbia Skytrain Station, Vancouver, Canada`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Commercial–Broadway Skytrain Station, Vancouver, Canada`,
//       `Commercial–Broadway Skytrain Station, Vancouver, Canada`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Coquitlam Central Skytrain Station, Vancouver, Canada`,
//       `Coquitlam Central Skytrain Station, Vancouver, Canada`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Edmonds Skytrain Station, Vancouver, Canada`,
//       `Edmonds Skytrain Station, Vancouver, Canada`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Gateway Skytrain Station, Vancouver, Canada`,
//       `Gateway Skytrain Station, Vancouver, Canada`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Gilmore Skytrain Station, Vancouver, Canada`,
//       `Gilmore Skytrain Station, Vancouver, Canada`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Granville Skytrain Station, Vancouver, Canada`,
//       `Granville Skytrain Station, Vancouver, Canada`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Holdom Skytrain Station, Vancouver, Canada`,
//       `Holdom Skytrain Station, Vancouver, Canada`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Inlet Centre Skytrain Station, Vancouver, Canada`,
//       `Inlet Centre Skytrain Station, Vancouver, Canada`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Joyce–Collingwood[d] Skytrain Station, Vancouver, Canada`,
//       `Joyce–Collingwood[d] Skytrain Station, Vancouver, Canada`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `King Edward Skytrain Station, Vancouver, Canada`,
//       `King Edward Skytrain Station, Vancouver, Canada`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `King George Skytrain Station, Vancouver, Canada`,
//       `King George Skytrain Station, Vancouver, Canada`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Lafarge Lake–Douglas Skytrain Station, Vancouver, Canada`,
//       `Lafarge Lake–Douglas Skytrain Station, Vancouver, Canada`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Lake City Way Skytrain Station, Vancouver, Canada`,
//       `Lake City Way Skytrain Station, Vancouver, Canada`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Langara–49th Avenue Skytrain Station, Vancouver, Canada`,
//       `Langara–49th Avenue Skytrain Station, Vancouver, Canada`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Lansdowne Skytrain Station, Vancouver, Canada`,
//       `Lansdowne Skytrain Station, Vancouver, Canada`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Lincoln Skytrain Station, Vancouver, Canada`,
//       `Lincoln Skytrain Station, Vancouver, Canada`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Lougheed Town Centre Skytrain Station, Vancouver, Canada`,
//       `Lougheed Town Centre Skytrain Station, Vancouver, Canada`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Main Street–Science World Skytrain Station, Vancouver, Canada`,
//       `Main Street–Science World Skytrain Station, Vancouver, Canada`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Marine Drive Skytrain Station, Vancouver, Canada`,
//       `Marine Drive Skytrain Station, Vancouver, Canada`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Metrotown Skytrain Station, Vancouver, Canada`,
//       `Metrotown Skytrain Station, Vancouver, Canada`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Moody Centre Skytrain Station, Vancouver, Canada`,
//       `Moody Centre Skytrain Station, Vancouver, Canada`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Nanaimo Skytrain Station, Vancouver, Canada`,
//       `Nanaimo Skytrain Station, Vancouver, Canada`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `New Westminster Skytrain Station, Vancouver, Canada`,
//       `New Westminster Skytrain Station, Vancouver, Canada`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Oakridge–41st Avenue Skytrain Station, Vancouver, Canada`,
//       `Oakridge–41st Avenue Skytrain Station, Vancouver, Canada`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Olympic Village Skytrain Station, Vancouver, Canada`,
//       `Olympic Village Skytrain Station, Vancouver, Canada`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Patterson Skytrain Station, Vancouver, Canada`,
//       `Patterson Skytrain Station, Vancouver, Canada`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Production Way–University Skytrain Station, Vancouver, Canada`,
//       `Production Way–University Skytrain Station, Vancouver, Canada`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Renfrew Skytrain Station, Vancouver, Canada`,
//       `Renfrew Skytrain Station, Vancouver, Canada`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Richmond–Brighouse Skytrain Station, Vancouver, Canada`,
//       `Richmond–Brighouse Skytrain Station, Vancouver, Canada`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Royal Oak Skytrain Station, Vancouver, Canada`,
//       `Royal Oak Skytrain Station, Vancouver, Canada`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Rupert Skytrain Station, Vancouver, Canada`,
//       `Rupert Skytrain Station, Vancouver, Canada`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Sapperton Skytrain Station, Vancouver, Canada`,
//       `Sapperton Skytrain Station, Vancouver, Canada`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Scott Road Skytrain Station, Vancouver, Canada`,
//       `Scott Road Skytrain Station, Vancouver, Canada`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Sea Island Centre Skytrain Station, Vancouver, Canada`,
//       `Sea Island Centre Skytrain Station, Vancouver, Canada`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Sperling–Burnaby Lake Skytrain Station, Vancouver, Canada`,
//       `Sperling–Burnaby Lake Skytrain Station, Vancouver, Canada`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Stadium–Chinatown Skytrain Station, Vancouver, Canada`,
//       `Stadium–Chinatown Skytrain Station, Vancouver, Canada`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Surrey Central Skytrain Station, Vancouver, Canada`,
//       `Surrey Central Skytrain Station, Vancouver, Canada`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Templeton Skytrain Station, Vancouver, Canada`,
//       `Templeton Skytrain Station, Vancouver, Canada`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Vancouver City Centre Skytrain Station, Vancouver, Canada`,
//       `Vancouver City Centre Skytrain Station, Vancouver, Canada`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `VCC–Clark Skytrain Station, Vancouver, Canada`,
//       `VCC–Clark Skytrain Station, Vancouver, Canada`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Waterfront Skytrain Station, Vancouver, Canada`,
//       `Waterfront Skytrain Station, Vancouver, Canada`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Yaletown–Roundhouse Skytrain Station, Vancouver, Canada`,
//       `Yaletown–Roundhouse Skytrain Station, Vancouver, Canada`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `YVR–Airport Skytrain Station, Vancouver, Canada`,
//       `YVR–Airport Skytrain Station, Vancouver, Canada`,
//       null,
//       null,
//       null,
//     ],
//   ],
// };

// Data to scrape.
// db = {
//   geo: [
//     [
//       `Shangri-La's Rasa Sentosa Resort & Spa`,
//       `101 Siloso Road Sentosa, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Orchard Hotel Singapore`,
//       `442 Orchard Road, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Pan Pacific Singapore`,
//       `7 Raffles Boulevard, Marina Square, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `PARKROYAL COLLECTION Pickering, Singapore`,
//       `3 Upper Pickering Street, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [`M Social Singapore`, `90 Robertson Quay, Singapore`, null, null, null],
//     [
//       `The Fullerton Hotel Singapore`,
//       `1 Fullerton Square, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [`W Singapore - Sentosa Cove`, `21 Ocean Way, Singapore`, null, null, null],
//     [
//       `Carlton Hotel Singapore`,
//       `76 Bras Basah Road, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Shangri-La Hotel, Singapore`,
//       `22 Orange Grove Road, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Marina Bay Sands`,
//       `BAYFRONT AVENUE, 10, Singapore, SIN`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `PARKROYAL COLLECTION Marina Bay, Singapore`,
//       `6 Raffles Boulevard Marina Square, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `JEN Singapore Tanglin by Shangri-La`,
//       `1A Cuscaden Road, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [`Hilton Singapore`, `581 Orchard Road, Singapore`, null, null, null],
//     [
//       `Andaz Singapore - a concept by Hyatt`,
//       `5 Fraser Street, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [`Hotel Boss`, `500 Jalan Sultan Road, Singapore`, null, null, null],
//     [
//       `Travelodge Harbourfront`,
//       `50 Telok Blangah Road, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `The Ritz-Carlton, Millenia Singapore`,
//       `7 Raffles Avenue, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Sofitel Singapore Sentosa Resort & Spa`,
//       `2 Bukit Manis Road Sentosa Island, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Oakwood Premier AMTD Singapore`,
//       `6 Shenton Way OUE Downtown 1, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `The Westin Singapore`,
//       `12 Marina View, Asia Square Tower 2, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Amara Sanctuary Resort Sentosa`,
//       `1 Larkhill Road, Sentosa Island, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `One Farrer Hotel`,
//       `1 Farrer Park Station Road, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Conrad Centennial Singapore`,
//       `Two Temasek Boulevard, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [`Grand Hyatt Singapore`, `10 Scotts Road, Singapore`, null, null, null],
//     [
//       `Four Seasons Hotel Singapore`,
//       `190 Orchard Boulevard, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `YOTEL Singapore Orchard Road`,
//       `366 Orchard Road, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `InterContinental Singapore`,
//       `80 Middle Road, Bugis Junction, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [`Hotel G Singapore`, `200 Middle Road, Singapore`, null, null, null],
//     [
//       `Village Hotel Sentosa by Far East Hospitality`,
//       `10 Artillery Avenue, #02-01, Sentosa Island, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Capella Singapore`,
//       `1 The Knolls, Sentosa Island, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [`The St. Regis Singapore`, `29 Tanglin Road, Singapore`, null, null, null],
//     [`PARKROYAL on Beach Road`, `7500 Beach Road, Singapore`, null, null, null],
//     [
//       `Oasia Hotel Downtown Singapore`,
//       `100 Peck Seah Street, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Village Hotel Bugis by Far East Hospitality`,
//       `390 Victoria Street, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `YotelAir Changi`,
//       `78 Airport Boulevard, Changi, #04-280, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [`Goodwood Park Hotel`, `22 Scotts Road, Singapore`, null, null, null],
//     [
//       `Hotel Bencoolen@Hong Kong Street`,
//       `47 Hongkong Street, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `five6 Hotel Splendour`,
//       `5 Lorong 6 Geylang, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Four Points by Sheraton Singapore, Riverview`,
//       `382 Havelock Road, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [`Dorsett Singapore`, `333 New Bridge Road, Singapore`, null, null, null],
//     [`The Fullerton Bay Hotel`, `80 Collyer Quay, Singapore`, null, null, null],
//     [
//       `JW Marriott Hotel Singapore South Beach`,
//       `30 Beach Road, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [`Hotel Fort Canning`, `11 Canning Walk, Singapore`, null, null, null],
//     [
//       `Ambassador Transit Hotel Terminal 3`,
//       `Singapore Changi Airport, PTB3, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `The Barracks Hotel Sentosa by Far East Hospitality`,
//       `2 Gunner Lane, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [`M Hotel Singapore`, `81 Anson Road, Singapore`, null, null, null],
//     [
//       `JEN Singapore Orchardgateway by Shangri-La`,
//       `277 Orchard Road, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [`Park Hotel Alexandra`, `323 Alexandra Road, Singapore`, null, null, null],
//     [
//       `Crowne Plaza Changi Airport`,
//       `75 Airport Boulevard, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `The Southbridge Hotel`,
//       `210 South Bridge Road, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `lyf Funan Singapore by Ascott`,
//       `67 HILL STREET, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Resorts World Sentosa - Equarius Hotel`,
//       `8 Sentosa Gateway, Sentosa Island, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `JI HOTEL ORCHARD SINGAPORE`,
//       `11 Penang Lane Singapore 238485, Singapore, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [`Lloyd's Inn`, `2 Lloyd Road, Singapore`, null, null, null],
//     [
//       `Swissotel The Stamford, Singapore`,
//       `2 Stamford Road, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Orchard Rendezvous Hotel by Far East Hospitality`,
//       `1 Tanglin Road, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Sheraton Towers Singapore`,
//       `39 Scotts Road, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [`Aqueen Hotel Paya Lebar`, `33 Jalan Afifi, Singapore`, null, null, null],
//     [
//       `Venue Hotel - The Lily`,
//       `238 Joo Chiat Road, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [`Grand Park Orchard`, `270 Orchard Road, Singapore`, null, null, null],
//     [
//       `The Outpost Hotel Sentosa by Far East Hospitality`,
//       `10 Artillery Avenue, #03-01, Sentosa Island, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Days Hotel by Wyndham Singapore at Zhongshan Park`,
//       `1 Jalan Rajah, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Hotel 1887 The New Opera House`,
//       `25 Trengganu Street, Entrance on Smith Street, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [`Duxton Reserve Singapore`, `83 Duxton Road, Singapore`, null, null, null],
//     [`Hotel Calmo Bugis`, `95 Beach Rd, Singapore`, null, null, null],
//     [
//       `InterContinental Singapore Robertson Quay`,
//       `1 Nanson Road, at Robertson Quay, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Resorts World Sentosa - Equarius Hotel`,
//       `8 Sentosa Gateway, Sentosa Island, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [`Furama RiverFront`, `405 Havelock Road, Singapore`, null, null, null],
//     [
//       `Q Loft Hotel1929@Chinatown`,
//       `50 Keong Saik Road, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Mandarin Orchard Singapore`,
//       `333 Orchard Road, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `ibis budget Singapore Clarke Quay`,
//       `20 Hong Kong Street, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [`Amara Singapore`, `165 Tanjong Pagar Road, Singapore`, null, null, null],
//     [
//       `The Warehouse Hotel`,
//       `320 Havelock Road Robertson Quay, Singapore, SIN`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Hilton Garden Inn Singapore Serangoon`,
//       `3 Belilios Road, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Sofitel Singapore City Centre`,
//       `9 Wallich Street, Singapore, SG`,
//       null,
//       null,
//       null,
//     ],
//     [`Fairmont Singapore`, `80 Bras Basah Road, Singapore`, null, null, null],
//     [`Venue Hotel`, `305 Joo Chiat Road, Singapore`, null, null, null],
//     [
//       `D'Resort at Downtown East`,
//       `1 Pasir Ris Close, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Fragrance Hotel - Classic`,
//       `418 Balestier Road, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [`K2 Guest House`, `15 South Buona Vista Rd, Singapore`, null, null, null],
//     [
//       `Peninsula Excelsior Hotel`,
//       `5 Coleman Street, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Park Hotel Farrer Park`,
//       `10 Farrer Park Station Road, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `SO/ Sofitel Singapore`,
//       `35 Robinson Road, (Drop off Point - Boon Tat Link), Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Fragrance Hotel - Oasis`,
//       `435 Balestier Road, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Resorts World Sentosa - Festive Hotel`,
//       `8 Sentosa Gateway, Resorts World Sentosa, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Holiday Inn Singapore Atrium`,
//       `317 Outram Road, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Royal Plaza on Scotts`,
//       `25 Scotts Road, Orchard, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Hotel Indigo Singapore Katong`,
//       `86 East Coast Road, Katong Square, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [`Naumi Hotel`, `41 Seah Street, Singapore`, null, null, null],
//     [
//       `The Vagabond Club, Singapore, a Tribute Portfolio Hotel`,
//       `39 Syed Alwi Road, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Village Hotel Katong by Far East Hospitality`,
//       `25 Marine Parade, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Furama City Centre`,
//       `60 Eu Tong Sen Street, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [`Park Hotel Clarke Quay`, `1 Unity Street, Singapore`, null, null, null],
//     [`Nostalgia Hotel`, `77 Tiong Bahru Road, Singapore`, null, null, null],
//     [`Champion Hotel City`, `37 North Canal Road, Singapore`, null, null, null],
//     [
//       `ST Signature Lite Jalan Besar`,
//       `15 Upper Weld Rd, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [`Studio M Hotel`, `3 Nanson Road, Singapore`, null, null, null],
//     [`Hmlet Cantonment`, `150 Cantonment Road, Singapore`, null, null, null],
//     [`Hotel Grand Central`, `22 Cavenagh Road, Singapore`, null, null, null],
//     [`The Sultan`, `101 Jalan Sultan, Singapore`, null, null, null],
//     [`Villa Samadhi`, `20 Labrador Villa Road, Singapore`, null, null, null],
//     [
//       `Park 22 Hotel Little India`,
//       `60 Kerbau Road, Singapore, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `AMOY by Far East Hospitality`,
//       `76 Telok Ayer Street, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Rendezvous Hotel Singapore`,
//       `9 Bras Basah Road, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [`New Cape Inn`, `Seng Poh Road,3, Singapore, SIN`, null, null, null],
//     [
//       `Courtyard by Marriott Singapore Novena`,
//       `99 Irrawaddy Road, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [`Orchid Country Club`, `1 Orchid Club Road, Singapore`, null, null, null],
//     [`Value Hotel Nice`, `302 Balestier Road, Singapore`, null, null, null],
//     [`V Hotel Bencoolen`, `48 Bencoolen Street, Singapore`, null, null, null],
//     [`ST Signature Tanjong Pagar`, `32 Tras St, Singapore`, null, null, null],
//     [`Arcadia Hotel`, `32 Hamilton Road, Singapore`, null, null, null],
//     [
//       `Swissotel Merchant Court`,
//       `20 Merchant Road, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `RELC International Hotel`,
//       `30 Orange Grove Rd, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Hotel 81 Premier Star`,
//       `31 Lorong 18 Geylang, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [`Hotel YAN`, `162 Tyrwhitt Road, Singapore`, null, null, null],
//     [
//       `Oasia Hotel Novena, Singapore`,
//       `8 Sinaran Drive, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `The Capitol Kempinski Hotel Singapore`,
//       `15 Stamford Road, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Resorts World Sentosa - Equarius Hotel`,
//       `8 Sentosa Gateway, Sentosa Island, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [`RedDoorz @ Aljunied`, `34 Lor 22 Geylang, Singapore`, null, null, null],
//     [`Hotel NuVe Heritage`, `13 Purvis Street, Singapore`, null, null, null],
//     [`Hotel Mono`, `18 Mosque Street #01-04, Singapore`, null, null, null],
//     [
//       `ibis budget Singapore Pearl`,
//       `21 Lorong 14 Geylang, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [`Arton Boutique Hotel`, `176 Tyrwhitt Road, Singapore`, null, null, null],
//     [`The Scarlet Singapore`, `33 Erskine Road, Singapore`, null, null, null],
//     [
//       `Holiday Inn Express Singapore Katong`,
//       `88 East Coast Road, Katong Square, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Populous Hotel @ Bugis`,
//       `23 Middle Rd, Singapore, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [`Mercure Singapore Bugis`, `122 Middle Road, Singapore`, null, null, null],
//     [`Hotel NuVe Urbane`, `3 King George's Ave, Singapore`, null, null, null],
//     [`Grand Park City Hall`, `10 Coleman Street, Singapore`, null, null, null],
//     [`ST Signature Bugis Beach`, `85 Beach Rd, Singapore`, null, null, null],
//     [
//       `Concorde Hotel Singapore`,
//       `100 Orchard Road, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [`Hotel Mi`, `41 Bencoolen Street, Singapore`, null, null, null],
//     [`Hotel NuVe Elements`, `41 Hongkong St, Singapore`, null, null, null],
//     [`V Hotel Lavender`, `70 Jellicoe Road, Singapore`, null, null, null],
//     [`York Hotel`, `21 Mount Elizabeth, Singapore`, null, null, null],
//     [
//       `Copthorne Kings Singapore`,
//       `403 Havelock Road, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Grand Copthorne Waterfront`,
//       `392 Havelock Road, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `RedDoorz Premium @ Serangoon`,
//       `3 Veerasamy Rd, Singapore, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `ibis Singapore On Bencoolen`,
//       `170 Bencoolen Street, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Siloso Beach Resort, Sentosa`,
//       `51 Imbiah Walk, Sentosa Island, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Grand Mercure Singapore Roxy`,
//       `50 East Coast Road, Roxy Square, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [`Park Regis Singapore`, `23 Merchant Road, Singapore`, null, null, null],
//     [`Naumi Liora Hotel`, `55 Keong Saik Road, Singapore`, null, null, null],
//     [
//       `Adamson Lodge - Hostel`,
//       `6 &amp; 7 Perak Road, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [`Quincy Hotel`, `22 Mount Elizabeth, Singapore`, null, null, null],
//     [`Regent Singapore`, `1 Cuscaden Road, Singapore`, null, null, null],
//     [
//       `Novotel Singapore on Stevens`,
//       `28 Stevens Road #01-01, Orchard District, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [`The Quay Hotel`, `57 South Bridge Road, Singapore`, null, null, null],
//     [`Changi Cove`, `351 Cranwell Road, Singapore`, null, null, null],
//     [`Rest Bugis Hotel`, `8 Jalan Kubor, Singapore`, null, null, null],
//     [
//       `Resorts World Sentosa - Crockfords Tower`,
//       `8 Sentosa Gateway, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `BEAT. Capsule Hostel @ Boat Quay`,
//       `50A Boat Quay, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Park Avenue Rochester`,
//       `31 Rochester Drive, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `One15 Marina Sentosa Cove Singapore`,
//       `#01-01, 11 Cove Drive, Sentosa Cove, Singapore, SIN`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Bliss Hotel Singapore`,
//       `62 Upper Cross Street, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [`Hotel Nuve`, `9 - 11A Jalan Pinang, Bugis, Singapore`, null, null, null],
//     [
//       `Citadines Rochor Singapore`,
//       `2 Serangoon Road, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Holiday Inn Singapore Orchard City Centre`,
//       `11 Cavenagh Road, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Village Hotel Albert Court by Far East Hospitality`,
//       `180 Albert Street, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [`BUTTERNUTTREE HOTEL`, `22 Teck Lim Road, Singapore`, null, null, null],
//     [
//       `PARKROYAL on Kitchener Road`,
//       `181 Kitchener Road, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [`Hotel Grand Pacific`, `101 Victoria Street, Singapore`, null, null, null],
//     [
//       `Winsland Serviced Suites by Lanson Place`,
//       `167 Penang Road, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Mercure Singapore On Stevens`,
//       `28 Stevens Road #01-02, Orchard, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [`S Inn Chinatown`, `52 Temple Street, Singapore`, null, null, null],
//     [`OSS Backpackers Hostel`, `9 Hamilton Rd, Singapore`, null, null, null],
//     [`Q Loft Hotels@Geylang`, `586 Geylang Rd, Singapore`, null, null, null],
//     [
//       `Hotel 1888 Collection`,
//       `20 Trengganu Street, 3rd Storey, Chinatown, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `MET A Space Pod @ Chinatown`,
//       `46b Smith Street, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `RedDoorz Premium @ Balestier`,
//       `387 Balestier Road, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [`Champion Hotel`, `60 Joo Chiat Road #01-06, Singapore`, null, null, null],
//     [
//       `Dream Lodge`,
//       `172 Tyrwhitt Road, Singapore, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [`Hotel 81 Sakura`, `181 Joo Chiat Road, Singapore`, null, null, null],
//     [`YMCA @ One Orchard`, `One Orchard Road, Singapore`, null, null, null],
//     [`Summer View Hotel`, `173 Bencoolen Street, Singapore`, null, null, null],
//     [
//       `The POD @ Beach Road`,
//       `289 Beach Road Level 3, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `ZEN Hostel Selegie`,
//       `11 Mackenzie Rd., G4 Station Hostel, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `7 Wonders Hostel at Upper Dickson`,
//       `12a Upper Dickson Rd, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [`Lodge 41`, `41 Lorong 16 Geylang, Singapore`, null, null, null],
//     [`HipsterCity Hostel`, `9 Circular Rd, Singapore`, null, null, null],
//     [`Hotel 81 Osaka`, `1 Eng Hoon Street, Singapore`, null, null, null],
//     [`Hotel 81 Orchid`, `21 Lorong 8, Geylang, Singapore`, null, null, null],
//     [`Spacepod@SG`, `12 Lorong 1 Geylang, Singapore`, null, null, null],
//     [
//       `Park Avenue Changi`,
//       `2 Changi Business Park Avenue 1, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `ZEN Rooms Clarke Quay`,
//       `42 Carpenter Street, Boat Quay, Located in Jayleen 1918, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Rucksack Inn @ Lavender`,
//       `280 Lavender Street, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `The Seacare Hotel`,
//       `52 Chin Swee Road, (Entrance via Jalan Kukuh), Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Destination Singapore Beach Road`,
//       `700 Beach Rd, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Hotel Clover 769 North Bridge Road`,
//       `769 North Bridge Road, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `RedDoorz near Marine Parade Cental`,
//       `400 East Coast Road, Marine Parade, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Beary Best! Chinatown by A Beary Good Hostel`,
//       `16 &amp; 18 Upper Cross Street, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [`RedDoorz @ Geylang`, `61 Westerhout Road, Singapore`, null, null, null],
//     [
//       `Carlton City Hotel Singapore`,
//       `1 Gopeng Street, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Holiday Inn Express Singapore Serangoon`,
//       `270 Jalan Besar, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Pine Hostel @ Lavender`,
//       `153A Tyrwhitt Road, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Hotel Royal @ Queens`,
//       `No. 12 Queen Street, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Holiday Inn Express Singapore Orchard Road`,
//       `20 Bideford Road, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [`The Club Hotel`, `28 ANN SIANG ROAD, Singapore, SIN`, null, null, null],
//     [
//       `G4 Station Backpackers' Hostel`,
//       `11 Mackenzie Road, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Parc Sovereign Hotel - Tyrwhitt`,
//       `165 Tyrwhitt Road, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `The Quay Hotel West Coast`,
//       `428 Pasir Panjang Road, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Reddoorz Hostel @ Beach Road`,
//       `285 Beach Road, Singapore, SIN`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `The Porcelain Hotel by JL Asia`,
//       `48 Mosque Street, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [`Hotel 81 Tristar`, `1 Onan Road, Singapore`, null, null, null],
//     [
//       `MET A Space Pod @ Boat Quay`,
//       `51A Boat Quay, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `ABC Premium Hostel`,
//       `91A, 93A &amp; 95A Owen Road, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Hotel 81 (Premier) Hollywood`,
//       `61 Lorong 8 Geylang, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Somerset Liang Court Singapore`,
//       `177b River Valley Road, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Capsule Pod Boutique Hostel`,
//       `38 Upper Cross Street, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `ibis budget Singapore Sapphire`,
//       `3 Lorong 10 Geylang, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Hotel Classic by Venue`,
//       `12 Joo Chiat Road, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `RedDoorz Plus Victoria Hotel`,
//       `87 Victoria Street, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [`Thad’s Boutique Hostel`, `259 Outram Road, Singapore`, null, null, null],
//     [`Royal Hostel`, `73A Pagoda Street, Singapore`, null, null, null],
//     [
//       `Parc Sovereign Hotel – Albert St`,
//       `175 Albert Street, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [`The Keong Saik Hotel`, `69 Keong Saik Road, Singapore`, null, null, null],
//     [
//       `ibis budget Singapore Emerald`,
//       `20 Lorong 6 Geylang, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [`JH Hotel`, `8 Lor 10 Geylang, Geylang, Singapore`, null, null, null],
//     [
//       `EIGHTEEN BY THREE CABINS`,
//       `No 3 Stanley Street #02-00, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Hotel Clover 33 Jalan Sultan`,
//       `33 Jalan Sultan, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `ZEN Premium Kampong Glam`,
//       `101 Jln Sultan, The Sultan, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `ZEN Premium Kallang`,
//       `Located in 5/6 Hotel Splendour, 5 Lor, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [`YWCA Fort Canning`, `6 Fort Canning Road, Singapore`, null, null, null],
//     [`Meadows Hostel`, `7A Hamilton Road, Singapore`, null, null, null],
//     [
//       `Bright Star Hotel`,
//       `No. 20 Lorong 17 Geylang, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Resorts World Sentosa - Genting Hotel Jurong`,
//       `2 Town Hall Link, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [`Chic Capsule Otel`, `13 Mosque Street, Singapore`, null, null, null],
//     [
//       `Hotel Miramar Singapore`,
//       `401 Havelock Road, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Hotel Chancellor@Orchard`,
//       `28 Cavenagh Road, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Hotel Re! @ Pearl's Hill`,
//       `175A Chin Swee Road, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [`Perak Hotel`, `12 Perak Road, Singapore`, null, null, null],
//     [
//       `ST Signature Lite Jalan Besar`,
//       `15 Upper Weld Rd, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Hotel Clover The Arts`,
//       `58 South Bridge Road, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Capri By Fraser China Square, Singapore`,
//       `181 South Bridge Road, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Hangout @ Mt.Emily`,
//       `10A Upper Wilkie Road, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Reddoorz Premium @ Balestier`,
//       `387 BALESTIER ROAD, Singapore, SIN`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `ibis budget Singapore Joo Chiat`,
//       `219 Joo Chiat Road, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [`ZEN Rooms Stevens Road`, `60 Stevens Road, Singapore`, null, null, null],
//     [`K Space Inn 14`, `14 Circular Rd, Singapore`, null, null, null],
//     [`Atlantis Pods at Chinatown`, `52 Pagoda St, Singapore`, null, null, null],
//     [
//       `ZEN Rooms Orchard`,
//       `30 Orange Grove Road, RELC International Hotel, Singapore, Orchard`,
//       null,
//       null,
//       null,
//     ],
//     [`Rest House`, `133 Serangoon Garden Way, Singapore`, null, null, null],
//     [
//       `Santa Grand Hotel East Coast`,
//       `171 East Coast Road, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Backpackers' Inn Chinatown`,
//       `27 Mosque Street, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Aqueen Heritage Hotel Joo Chiat`,
//       `51 Joo Chiat Road, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Hotel Clover 5 HongKong Street`,
//       `5 Hongkong Street, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [`Cube @ Kampong Glam`, `55 Bussorah St., Singapore`, null, null, null],
//     [`Jayleen 1918 Hotel`, `42 Carpenter Street, Singapore`, null, null, null],
//     [
//       `ZEN Rooms Boat Quay`,
//       `Located in The Quay Hotel, South Bridge Road, Number 57, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `River City Inn - Hostel`,
//       `33C Hongkong Street, 4th Floor without a lift, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Royal Lodge @ Pagoda Street - Hostel`,
//       `66A &amp; 66B Pagoda Street, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Bond Boutique Capsule Hotel at Bugis - Hostel`,
//       `7A Jalan Pinang Singapore 199139, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [`The Elizabeth Hotel`, `24 Mount Elizabeth, Singapore`, null, null, null],
//     [`ibis Singapore Novena`, `6 Irrawaddy Road, Singapore`, null, null, null],
//     [
//       `ibis budget Singapore Ruby`,
//       `10 Lorong 20 Geylang, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `Beary Best! Hostel Kampong Glam`,
//       `64 Arab St, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `RedDoorz Hostel @ Little India`,
//       `60 Race Course Road, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [`Golden Hostel`, `146 Jalan Bukit Merah, Singapore`, null, null, null],
//     [
//       `Jayleen Clarke Quay Hotel`,
//       `25 New Bridge Road, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [`Adler Hostel`, `259 South Bridge Road, Singapore`, null, null, null],
//     [
//       `ZEN Hostel Aljunied`,
//       `Located in Lodge 41, 41 Lorong 16 Geylang, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `ibis budget Singapore Crystal`,
//       `50 Lorong 18 Geylang, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [`JetQuay Suites`, `60 Airport Blvd, Singapore`, null, null, null],
//     [`Snooze Inn Dickson Road`, `43 Dickson Rd, Singapore`, null, null, null],
//     [
//       `Orchid Hotel`,
//       `1 Tras Link (Tanjong Pagar), Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [`Link Hotel`, `50 Tiong Bahru Road, Singapore`, null, null, null],
//     [
//       `Wanderloft Capsule Hostel`,
//       `49A South Bridge Rd, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [`7 Wonders Hostel`, `257 Jalan Besar, Singapore`, null, null, null],
//     [`Hotel 81 Gold`, `20 Lorong 20 Geylang, Singapore`, null, null, null],
//     [`Hotel Clover 7`, `7 Hong Kong Street, Singapore`, null, null, null],
//     [`Hotel Kai`, `14 Purvis Street, Singapore`, null, null, null],
//     [`Ann Siang House`, `28 Ann Siang Road, Singapore`, null, null, null],
//     [
//       `Blanc Inn`,
//       `151 Tyrwhitt Road, (Lavender MRT Station), Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [`Gap Year Hostel`, `322 Lavender Street, Singapore`, null, null, null],
//     [`Ark Hostel`, `89 Geylang Road, Singapore`, null, null, null],
//     [`S Inn Clarke Quay`, `38-A Hong Kong Street, Singapore`, null, null, null],
//     [
//       `ZEN Hostel Little India - Hostel`,
//       `28 Madras Street, Little India, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `BEAT. Sports Hostel`,
//       `290A Jalan Besar Road, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [`Bunc Hostel`, `15 Upper Weld Road, Singapore`, null, null, null],
//     [`Aqueen Hotel Kitchener`, `230 Jalan Besar, Singapore`, null, null, null],
//     [`60's Hostel`, `569 Serangoon Road, Singapore`, null, null, null],
//     [
//       `Harbour Ville Hotel`,
//       `512 Kampong Bahru Road, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [`ZEN Rooms Novena`, `36 Newton Rd, Singapore`, null, null, null],
//     [`Circular House`, `6 Circular Rd, Singapore`, null, null, null],
//     [
//       `ZEN Rooms People's Park Complex`,
//       `48 Mosque St, Located in Porcelain Hotel by JL As, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `ZEN Hostel Clarke Quay`,
//       `Located in River City Inn, 33C Hong Kong Street Level 4, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [
//       `5footway.inn Project Chinatown 1`,
//       `63A Pagoda Street, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [`The Daulat`, `16 Madras Street, Singapore`, null, null, null],
//     [`NNV Hostel`, `57 Lavender St, Singapore`, null, null, null],
//     [`RM Hotel`, `10 Tuas West Drive, Singapore`, null, null, null],
//     [
//       `Met A Space Pod @ Arab Street`,
//       `56 Arab Street, Singapore`,
//       null,
//       null,
//       null,
//     ],
//     [`The11room`, `6A Jalan Ayer Singapore, Singapore`, null, null, null],
//   ],
// };

// Looping scrape function.
const geocodeScrapeAll = async () => {
  for (let geoItem of db.geo) {
    // Delay 5 seconds.
    console.log("Fetching...");
    await delay(10000);

    // Get geocode data.
    axios
      .get("https://maps.googleapis.com/maps/api/geocode/json", {
        params: {
          address: geoItem[1],
          key: "AIzaSyCQUu01hvcUZo14XTn4dqKqW2sNG_fpGik",
          // components: "country:SG",
          // components: "country:CA",
        },
      })
      .then(function (response) {
        // Get the response.
        geoItem[2] = formattedAddress =
          response.data.results[0].formatted_address;
        geoItem[3] = response.data.results[0].geometry.location.lat;
        geoItem[4] = response.data.results[0].geometry.location.lng;

        // Create new cells.
        let newName = document.createElement("td");
        let newAddressInitial = document.createElement("td");
        let newAddressGeocode = document.createElement("td");
        let newLatitude = document.createElement("td");
        let newLongitude = document.createElement("td");
        newName.innerHTML = geoItem[0];
        newAddressInitial.innerHTML = geoItem[1];
        newAddressGeocode.innerHTML = geoItem[2];
        newLatitude.innerHTML = geoItem[3];
        newLongitude.innerHTML = geoItem[4];

        // Create new row.
        let newRow = document.createElement("tr");
        newRow.appendChild(newName);
        newRow.appendChild(newAddressInitial);
        newRow.appendChild(newAddressGeocode);
        newRow.appendChild(newLatitude);
        newRow.appendChild(newLongitude);

        // Add to table.
        let existingTable = document.getElementsByTagName("table")[0];
        existingTable.appendChild(newRow);
      })
      .catch(function (e) {
        console.log(geoItem[0] + ": " + e);
      });
  }
  console.log("Done!");
};

geocodeScrapeAll();
